version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0

  backend:
    image: typicode/json-server
    ports:
      - "3000:3000"
    volumes:
      - ./db.json:/data/db.json
    command: json-server --watch /data/db.json --host 0.0.0.0 --port 3000
